### ISSUE TITLE
npm script serve:universal tries to start non-existing server script

### ISSUE THREAD

**Issue by adebree** [fulls1z3/universal#1]
Package.json:
```
"serve:universal": "nodemon ./.server/server.js",
```

but in ./.server/ there is only spa-server.js

**Comment by fulls1z3** [comment]
Hi @adebree, server.js is the output of the webpack bundling process.

When you run `npm run serve` just after an universal build command, it will work.

**Comment by adebree** [comment]
ah right.. I wasn't expecting files to be generated next to a file that is maintained directly. Thanks for clearing that up.

**Comment by fulls1z3** [comment]
You're welcome, enjoy the Angular Universal 👍
