### ISSUE TITLE
how to add this to existing project

### ISSUE THREAD

**Issue by srivas418** [fulls1z3/universal#10]
I would like to add this SSR to my project. I used ng2-admin as a base. How can i add this SSR to my project.. Please help

**Comment by fulls1z3** [comment]
Hi @srivas418, actually it would be pretty difficult to answer this without knowing your project structure.

If you can, better try to use this project as a seed and copy your components/views/styles conforming to the project structure.

If not, try to stick as much as possible to the webpack configuration, where the magic is hidden.
