### ISSUE TITLE
environment variables

### ISSUE THREAD

**Issue by kaoz70** [fulls1z3/universal#100]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[x] Feature request
[ ] Documentation issue or request
```

**Current behavior**
I cant find a way to set variables depending on builds

**Expected/desired behavior**
A way to add something like environment variables for the development and production builds.

**Minimal reproduction of the problem with instructions**
NA

**What is the motivation / use case for changing the behavior?**
Set an API URL on localhost or some dev URL, and use another one for production, maybe the same way the angular-cli sets them up in the environments/ folder

**Environment**
* **Angular version:** 4.3.0

* **Browser:**
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

* **For Tooling issues:**
- Node version: 8.4.0
- Platform:  Windows

* Others:
NA

**Comment by juanmarin-co** [comment]
@kaoz70 do you found a way to achieve that ? Thanks

**Comment by kaoz70** [comment]
@juanpmarin No, I ended up changing them on every build, it would be great to see this implemented.

**Comment by juanmarin-co** [comment]
@kaoz70 https://webpack.js.org/plugins/normal-module-replacement-plugin/
Using that plugin it can be done, having multiple environment files like angular-cli does

**Comment by deefactorial** [comment]
This is my solution in your `./tools/build/webpack.config.js` define a function to get your constants from the settings or from an environment variable set using `cross-env` like `cross-env DEMO_MODE=true npm run serve:spa-hmr`

```js
const defineConstants = function (options, settings) {
    let stack;
    let demoMode;
    let applicationURL;
    switch (options.env) {
        case 'prod':
        case 'production':
            switch (options.mode) {
                case 'stage':
                case 'staging':
                    stack = JSON.stringify('staging');
                    demoMode = false;
                    applicationURL = JSON.stringify(settings.staging.applicationURL);
                    break;
                default:
                    stack = JSON.stringify('production');
                    demoMode = false;
                    applicationURL = JSON.stringify(settings.production.applicationURL);
            }
            break;
        default:
            stack = JSON.stringify('development');
            demoMode = process.env.DEMO_MODE;
            applicationURL = JSON.stringify(settings.development.applicationURL);
    }
    return {
        'DEMO_MODE': demoMode,
        'STACK': stack,
        'APPLICATION_URL': applicationURL,
    }
}
```

then in your plugins array in the `webpack.config.js` set the define plugin
```js
plugins: [
    new definePlugin(defineConstants(options, settings))
]
```

then in your `src/client/custom.typings.d.ts` define your constants
```js
declare const DEMO_MODE: boolean;
declare const STACK: string;
declare const APPLICATION_URL: string;
```
then anywhere in your app you can use Application URL: `${APPLICATION_URL}`
the only outstanding issue I have with this method is that when using hmr webpack won't detect a change in the constant, and the file where the change is has to be touched for webpack to register the change.

**Comment by fulls1z3** [comment]
#507
