### ISSUE TITLE
production build not working

### ISSUE THREAD

**Issue by theomathieubhvr** [fulls1z3/universal#11]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**

After a fresh git clone / npm install, I run `npm run build:universal-prod`

![screen shot 2017-05-09 at 5 37 09 pm](https://cloud.githubusercontent.com/assets/24896997/25874024/b7465aec-34de-11e7-9423-9f507a3dc1ee.png)
I get this issue 4 times.

![screen shot 2017-05-09 at 5 37 26 pm](https://cloud.githubusercontent.com/assets/24896997/25874028/ba5b0e08-34de-11e7-8890-38edb1123035.png)

Then :

![screen shot 2017-05-09 at 5 37 35 pm](https://cloud.githubusercontent.com/assets/24896997/25874044/c63ca98e-34de-11e7-9d7c-8de32400491d.png)

**Expected/desired behavior**

Build files ready for universal production server.

**Minimal reproduction of the problem with instructions**
`npm run build:universal-prod`

**Please tell us about your environment:**

Mac OS, yarn.

* **Angular version:** 4.1.0

* **Node (for AoT issues):** `node --version` =  6.9.1

Thanks !

PS : it might be that I don't completely understand how to run production. If so, I can create a PR modifying the readme.

**Comment by fulls1z3** [comment]
It's a known issue which arises today, this repo depends on the `harmony` branch of UglifyJs2 and it got somehow broken. If you visit the latest issues on that repo, you'll notice how everyone's builds are failing.

Commenting Uglify plugin from webpack config will help the prod build to be successful. Tomorrow, I'll have a look at the UglifyJs2 repo and try to solve this.

**Comment by theomathieubhvr** [comment]
Cool, thanks ! 

👍

**Comment by fulls1z3** [comment]
(*internal note*)
here's a list of links referencing the **major** crash on `UglifyJS`:
- https://github.com/webpack/webpack/issues/2545#issuecomment-300491370
- https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/33
- https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/32
- https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/31
- https://github.com/mishoo/UglifyJS2/issues/448#issuecomment-300403182

**Comment by Mahmoud-hassan87** [comment]
i have same issue

**Comment by fulls1z3** [comment]
@Mahmoud-hassan87 i'm still collecting information on this topic, seems like the new of UglifyJS broke many things.

Stay tuned.

**Comment by fulls1z3** [comment]
@theomathieubhvr @Mahmoud-hassan87 get the latest version and try to build. I temporarily commented the `UglifyJs` and it should run without a problem now.

**Comment by theomathieubhvr** [comment]
Thanks ! That's working now.

I don't know what to do with this issue, renaming it or closing it ?

I'll let you decide.

**Comment by fulls1z3** [comment]
Let's leave it because I could not reproduce it (using `fulls1z3/webpack` as a dependency). Let's keep this open for a few more days, and let's see.

**Comment by fulls1z3** [comment]
I solved this by forcing the `uglify-js` deps to use version `git://github.com/mishoo/UglifyJS2#harmony-v2.8.22`.

Get the latest version of this repository, and remove `webpack` and `uglify-js` dirs from `node_modules` and run `npm install`/`yarn` et voila!
