### ISSUE TITLE
how to run production universal server ?

### ISSUE THREAD

**Issue by theomathieubhvr** [fulls1z3/universal#12]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the README and search github for a similar issue or PR before submitting
[x] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Expected/desired behavior**

I'm not sure how to run the universal server once I have built it with `npm run build:universal-prod` (I have deactivated UglifyJS as you told me in #11).

**Minimal reproduction of the problem with instructions**
I tried `node .server/server.js` but when I go to http://localhost:8000 it tells me that some .cache files are not existing.

* **Angular version:** 4.1.0

* **Node (for AoT issues):** `node --version` =  6.9.1

Thanks for your help ! Again, when I know how, I will be submitting a PR to enhance the readme.

**Comment by fulls1z3** [comment]
@theomathieubhvr thanks for pointing this issue out, I've found what's happening under the hood. `fs.mkdir` fails while creating `./temp/cache`. If you create this directory manually and run `npm run serve` task, it should run without a problem.

It seems I'll need to fix the `@ngx-cache/fs-storage` but gonna publish a workaround on this repo asap.

**Comment by fulls1z3** [comment]
@theomathieubhvr update the repo, also update the dependencies (*`@ngx-cache/fs-storage` has been upgraded to `v0.4.0-beta.2` while `v0.4.0-beta.1` became history due to this bug*). It should run without a problem.
