### ISSUE TITLE
troubles adding an svg

### ISSUE THREAD

**Issue by jason-timios** [fulls1z3/universal#14]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**

add svg to src/client/assets
example css `background: url('../../assets/bg.svg') no-repeat center center;`
webpack fails to build with error: 
```
/home/<REDACTED>/Projects/<REDACTED>/node_modules/webpack/lib/TemplatedPathPlugin.js:69
                .replace(REGEXP_CHUNKHASH, withHashLength(getReplacer(chunkHash), chunkHashWithLength))
   ^
Error: Path variable [chunkhash] not implemented in this context: assets/bg.[chunkhash].svg
```

**Expected/desired behavior**

For the svg to show as a background using relative paths to describe where it should be found.

**Minimal reproduction of the problem with instructions**

`npm run build:spa-hmr`

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Ubuntu 17.04, VsCode, NPM
* **Angular version:** 2.0.X

Angular 4.10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by jason-timios** [comment]
Seems to be fixed by using [hash] instead of [chunkhash] in webpack.common.js

**Comment by fulls1z3** [comment]
@jason-candeo thank for reporting this, I'll check this soon.

**Comment by fulls1z3** [comment]
@jason-candeo  done 👍
