### ISSUE TITLE
add image assets

### ISSUE THREAD

**Issue by vlados** [fulls1z3/universal#149]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[x] Feature request
[ ] Documentation issue or request
```

**Current behavior**
Currently I am not seeing any code for processing images and optimizing images. 

**Expected/desired behavior**

1. Create folder /assets/imgages/
2. Put any image file
3. Link it from Angular or Sass
4. View it in browser as optimized image

**Comment by vlados** [comment]
How I can integrate https://github.com/tcoopman/image-webpack-loader for example?

**Comment by fulls1z3** [comment]
@vlados looks like it could be a good enhancement for [angular-webpack-config](https://github.com/angular-webpack-config)

I'm closing this in favor of https://github.com/ng-seed/angular-webpack-config/issues/32
