### ISSUE TITLE
deactivate lazy loading of modules for SEO with server rendering

### ISSUE THREAD

**Issue by Aventrue** [fulls1z3/universal#151]
How can I deactivate the lazy loading of a modul with angular universal?
As an example when I access the page "About" that I get then the full HTML content inside the first pageload.
I see that in the routes this modules are specified as lazy, which is good on the client side but by server rendering, everithing should be there in the first request.

```
{
    path: '',
    component: MainComponent,
    children: [
      {
        path: '',
        loadChildren: './components/+home/home.module#HomeModule'
      },
      {
        path: 'about',
        loadChildren: './components/+about/about.module#AboutModule'
      },
      {
        path: 'secure-page',
        loadChildren: './components/+secure/secure.module#SecureModule'
      }
    ],
    canActivateChild: [MetaGuard],
    data: {
      i18n: {
        isRoot: true
      }
    }
  }

```

**Comment by fulls1z3** [comment]
@Aventrue actually, when a certain page is requested, the appropriate page gets rendered. You can try this behavior by using the *view page source* feature of Chrome. Simply navigate to a certain page, right click, choose *view page source* and let Chrome open it on a new tab. Then, go to that tab, and press F5.

If that page is not subject to *authorization*, it will be rendered. However, if you try that on a page requiring *authorization*, it will not - that's the point.

However, if you really want to avoid lazy loading, angular.io contains documentation exactly for this purpose, feel free to have a look: https://angular.io/guide/router
