### ISSUE TITLE
where to put external .js files of plugins  to make it part of bundle

### ISSUE THREAD

**Issue by Vikasbansal1234** [fulls1z3/universal#152]
I am using external plugins for animation having js and css files but I  dont know where should I put these .js files in project so that it would become of part of bundle created by build .Please let me know. like Modernizer,TweenMax. etc

**Comment by gianpaj** [comment]
see `/universal/tools/config/html-elements.config.js` and issue #125

**Comment by fulls1z3** [comment]
@Vikasbansal1234 thanks 👍
