### ISSUE TITLE
allow PORT configuration at app startup

### ISSUE THREAD

**Issue by Angry-Potato** [fulls1z3/universal#156]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[x ] Documentation issue or request
```

**Current behavior**

Setting env variable PORT to a desired value prior to running `npm run serve` has no impact on the app.

**Expected/desired behavior**

Setting PORT env variable before running `npm run serve` configures the express server to listen on the specified port.

**What is the motivation / use case for changing the behavior?**

I am still a noob to webpack and angular 2 so I apologise if this is a dumb question. I am aware that setting the environment variable PORT at build time will bake the PORT into the app. Unfortunately, I only know which PORT to expose at app startup. This is a restriction imposed on me by my hosting platform, and I feel not an unreasonable one. I am pretty sure this is very possible, and probably quite a common use case, I just can't find the appropriate docs and my experiments have yielded no fruit!

**Environment**
* **Angular version:** 4.4.1

**Comment by Angry-Potato** [comment]
for anyone with a similar issue who happens to end up here, use @rallu 's fork of angular webpack config https://github.com/rallu/angular-webpack-config which removes the defineplugin, and redefine it yourself in webpack.config.js as

```
      new webpack.DefinePlugin({
        'ENV': JSON.stringify('production'),
        'process.env.ENV': JSON.stringify('production'),
        'process.env.NODE_ENV': JSON.stringify('production'),
        'process.env.HOST': JSON.stringify(settings.host)
      }),
```

this leaves `process.env.PORT` intact in the server code.

**Comment by rallu** [comment]
Having DefinePlugin in the project that has NodeJS server is a bad idea in my opinion. It prevents use cases like this (I had the same problem) and other cases where you need really to have system ENV variables for you.

I would suggest that ng-seed/universal would build their own env system totally separate from system ENV.

**Comment by Angry-Potato** [comment]
I agree, I only suggest putting DefinePlugin back in as a few things broke without it, and fixing them is beyond me (too lazy) at the moment.

**Comment by fulls1z3** [comment]
@Angry-Potato @rallu actually it's possible to override plugins right at the [webpack.config.js](https://github.com/ng-seed/universal/blob/master/tools/build/webpack.config.js).

on https://github.com/ng-seed/universal/blob/master/tools/build/webpack.config.js#L71, https://github.com/ng-seed/universal/blob/master/tools/build/webpack.config.js#L74 and https://github.com/ng-seed/universal/blob/master/tools/build/webpack.config.js#L77 the `UglifyJsPlugin` has been removed from the **staging** mode.

In order to override `DefinePlugin`, simply add it to the `plugins` array of [webpack.config.js](https://github.com/ng-seed/universal/blob/master/tools/build/webpack.config.js) so you can more or less reach the same goal:

```javascript
const browserConfig = function(root, settings) {
  return {
    plugins: [
      new webpack.DefinePlugin({
        /* desired configuration */
      }),

      /* other plugins */
  };
};

const serverConfig = function(root, settings) {
  return {
    plugins: [
      new webpack.DefinePlugin({
        /* desired configuration */
      }),

      /* other plugins */
  };
};

/* any other code */

module.exports = function(options, root, settings) {
  switch (options.env) {
    /* ... */
      ? webpackMerge({
        customizeArray: mergePlugins(['DefinePlugin'])
      })(webpackConfig.universal.server.prod(root, settings), serverConfig(root, settings))
      : webpackMerge({
        customizeArray: mergePlugins(['DefinePlugin'])
      })(webpackConfig.universal.browser.prod(root, settings), browserConfig(root, settings))
    : webpackMerge({
      customizeArray: mergePlugins(['DefinePlugin'])
    })(webpackConfig.spa.prod(root, settings), browserConfig(root, settings))
    /* ... */
  }
};
```

**Comment by fulls1z3** [comment]
@Angry-Potato @rallu if you feel that an own env system totally separate from system ENV, you can always contribute with your use cases/ideas as well as PRs to this repo and [angular-webpack-config](angular-webpack-config).
