### ISSUE TITLE
will src/server code logic be exposed?

### ISSUE THREAD

**Issue by calebeaires** [fulls1z3/universal#159]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[x] Documentation issue or request
```

**Question**:
I have made some confusion about what ng-seed/universal (Angular Universal) can do. Is it just an pre-render application or it is a full secury server side endpoint? Can I built an app using Angular Universal with no worries if the user will know about my app logic? Can I replace my Express server side that handle user login with the Angular Universal? How does it compare with Meteor isomorphic way to do things?

**Expected/desired behavior**
Write an front-end and back-end using Angular Universal that back-end controllers/code will not be exposed to the final user.

**Comment by fulls1z3** [comment]
@calebeaires I think I understand what you meant. The answer is, yes any logic on an Angular project is exposed to the public.

It's one of the common best practices to to separate back-end and front-end from each other. When you need to perform some server-side logic, leverage the advantage of REST APIs - with appropriate authentication/authorization implementation, the REST APIs will stay secure.
