### ISSUE TITLE
changes do not impact the view and HMR is not working anymore

### ISSUE THREAD

**Issue by theomathieubhvr** [fulls1z3/universal#16]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**

I don't know why but sometimes running `npm run serve:spa-hmr` the files are still at the last occurence. When changing files nothing happens on http://localhost:1337.

I tried to remove .cache and .temp directories, with no success.

Any idea why ?

When I clone your repo again and then yarn, everything is working fine.

**Minimal reproduction of the problem with instructions**

I do not know how to reproduce :(

**Please tell us about your environment:**

Mac OS, VS Code, Yarn.

* **Angular version:** 4.1.0

* **Browser:** [all]

* **Node (for AoT issues):** `node --version` =   6.9.1

Thanks !

**Comment by fulls1z3** [comment]
@theomathieubhvr without repro steps it would be very difficult to see what's going on. I'll try to have a look on this when I'll be available.

**Comment by theomathieubhvr** [comment]
Yes I understand. I'll try to repro this on monday ! 

Thanks.

**Comment by theomathieubhvr** [comment]
Ok,

I succeeded repro this :)

I THINK it might be starting when I run `npm run build:universal-prod`, then my hmr command does not work anymore.

This is what I did :
```bash
$ git clone ...
$ npm run build:spa-dev (to build index.html for the first time, or else hmr does not work).
$ npm run serve:spa-hmr
```

MODIFY A FILE : HMR WORKS

```bash
$ Ctrl-C
$ npm run build:universal-prod
$ node .server/server.js
```

MODIFYING A FILE DOES NOT WORK BEYOND THIS POINT.

```bash
$ npm run serve:spa-hmr
```
=> even when deleting .cache, .temp directories, any change is not taken into account (event if I change a file BEFORE running serve:spa-hmr).

Thanks :)

**Comment by fulls1z3** [comment]
@theomathieubhvr now I get it :)

The HMR feature does not run on the server platform (*Universal*) yet. I've got it working just on the browser platform (*SPA*). Let's keep this issue open, because I'm still working on development of polyfills for Angular Material for the server platform. Then, I'll surely have a look at this.

**Comment by theomathieubhvr** [comment]
Oh, that's not what I meant. I don't want hmr to work with universal. But in my case :

- I run hmr for development mode
- I run build:universal-prod for production mode 

But one at a time !

Once I runned build:universal-prod to build my project for production, I cannot develop anymore cause my files are not updated anymore.

**Comment by fulls1z3** [comment]
Now more clear, the HMR implementation was only for the **development mode** (*JiT*), and on **browser platform** (*SPA*).

**Comment by fulls1z3** [comment]
And I want to simply ask about `files not updated anymore`. You mean, the assets which were copied thru `CopyWebpackPlugin`?

**Comment by theomathieubhvr** [comment]
I've not tried the assets (I can try any file if you ask me) but modifying app.component.html does not  update the view.

**Comment by fulls1z3** [comment]
Understood, assets just add a bit more complexity to the current situation. But the previous answer is still valid, you can get the HMR running only after a development build, not a production build.

However, I'll see what can I do for this.

**Comment by theomathieubhvr** [comment]
Oh ok now I understand !!

I have to run build:spa-dev to rebuild the correct files.

As always, thanks for your reactivity ! :)
