### ISSUE TITLE
_

### ISSUE THREAD

**Issue by ghost** [fulls1z3/universal#160]
_

**Comment by fulls1z3** [comment]
@megamindbrian the SASS files which are included in this repo are still experimental, and functionality/layout is subject to changes soon. I see, there's a lack of documentation for the SASS files, and we should cover it somehow.

For now, I could suggest you to play with [ViewEncapsulation](https://angular.io/api/core/ViewEncapsulation) at the components - at least this will allow you to use global styles.

**Comment by megamindbrian** [comment]
I ended up having to reimport all the core styles because core doesn't add
encapsulation like the theme does.
