### ISSUE TITLE
reorder dependencies in package.json

### ISSUE THREAD

**Issue by theomathieubhvr** [fulls1z3/universal#17]
Hey,

I would like to create a Pull Request to reorder the devDependencies (alphabetically) in your package.json.

The reason behind this is that yarn automatically do that and it creates huge conflict when git fetching your repo into my private one.

Do you agree ? If so, I will create a PR ASAP.

**Comment by fulls1z3** [comment]
@theomathieubhvr I saw that `yarn` is auto-sorting the deps using `yarn upgrade` but the main reason that the deps are not sorted, just grouped, was the ability to manage them by seeing in groups.

It's in my mind to find out a way how to make `yarn` to not sort them alphabetically. For now, let's better leave it :)

**Comment by theomathieubhvr** [comment]
Ok ! 

Thanks for the explanation.
