### ISSUE TITLE
fonts are not loaded in browser

### ISSUE THREAD

**Issue by vlados** [fulls1z3/universal#173]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
```

**Current behavior**
Currently when I add some local fonts to the css they are copied to /public/assets/assets but in the compiled css it's trying to load  http://localhost:1337/assets/assets/assets/ubuntu-regular-webfont.639f70ec3b8abfce8b7805773583dd42.woff2

If I try to change /tools/build/build-conf.json and set publicPaths to /assets/ it's loading the fonts correctly but its breaking the hot reload ...
I've tried adding rule for the fonts in webpack.conf.js in the rules section but it's not applying 

**Expected/desired behavior**
Load the font correctly in the browser

**Comment by fulls1z3** [comment]
@vlados I understood the use case you need to get this working. Closing this issue, as it's going to be tracked on https://github.com/ng-seed/angular-webpack-config/issues/33
