### ISSUE TITLE
await universal-compliant ngx-perfect-scrollbar

### ISSUE THREAD

**Issue by degendeveloperatwork** [fulls1z3/universal#175]
For Angular Universal, when you look the content is wrapped up in *ngIf="isBrowser"  is not outputted in "open source" -> view-source:http://localhost:8000 , but to my understanding, it should be as it is Angular Universal.

**Comment by fulls1z3** [comment]
@ChrisTarasovs there was an implementation of *ngx-perfect-scrollbar* which was non-universal-compliant at the moment those pages were committed. Wrapping it up with `*ngIf="isBrowser"` was the only way to prevent it being processed by the server bundle.

Actually, you found out a great point - we have to keep an eye open on the status of *ngx-perfect-scrollbar*, and remove those wrappers at the moment it becomes universal-compliant.
