### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by rahulmodu** [fulls1z3/universal#178]
using version 
npm -v  =>   5.3.0
node -v  =>  v6.11.1
i am getting error while creating a build of 
'build:spa-prod'
error coming===>>   ERROR { ReferenceError: window is not defined

i have used isBrowser check.
how can i fix this problem.

**Comment by fulls1z3** [comment]
@rahulmodu any non-universal-compliant library can cause this error. You need to test the external libraries one-by-one and find the failing one.
