### ISSUE TITLE
how include primeNG

### ISSUE THREAD

**Issue by hameltomor** [fulls1z3/universal#18]
Hi guys!

How I can use primeNG modules with this template?

I installed to project and registered in module, but I have a error when I started like universal server.
`VM32464:27 ERROR Error: Uncaught (in promise): Error: Unexpected value 'DropdownModule' imported by the module 'BlogModule'. Please add a @NgModule annotation.
Error: Unexpected value 'DropdownModule' imported by the module 'BlogModule'. Please add a @NgModule annotation.`

**Comment by fulls1z3** [comment]
@hameltomor unfortunately I have no specific knowledge about primeNG. However, I'll update this repository by including @angular/material2 soon. I hope this future update would give you more or less an idea including primeNG.
