### ISSUE TITLE
integrate ngrx/store-devtools

### ISSUE THREAD

**Issue by ChrisTarasovsAngularDev** [fulls1z3/universal#180]
Is there a way to intergrate ngrx/store-devtools so I am to see the state in http://extension.remotedev.io/

**Comment by fulls1z3** [comment]
@ChrisTarasovsAngularDev if i remember correctly, this was included in earlier commits. However, it was removed due to broken builds while upgrading the Angular version.

Actually we can put this again on our roadmap, but it needs high level of caution.

**Comment by degendeveloperatwork** [comment]
@fulls1z3 after spending a lot of hours a found a way to get it integrated and now testing it :)

**Comment by bnlambert** [comment]
Please share

**Comment by fulls1z3** [comment]
@ChrisTarasovs these are great news, would you consider firing a PR including your changes?

**Comment by degendeveloperatwork** [comment]
1. Run npm i @ngrx/store-devtools --save to install the module.
2. Add StoreDevtoolsModule.instrument() to the end imports array in CoreModule.
3. Rebuild and serve (npm run build:universal-dev && npm run serve).
You need upgrade your ngrx store also to 4.0.0

**Comment by degendeveloperatwork** [comment]
If you run into errors saying dispatch missing, then u need the 4.0.0 version and then if you get error something that the reducer is missing then you run this on the command line:

`sudo o npm un -D @ngrx/{core,store,store-devtools} & sudo  & npm i -D @ngrx/{store,store-devtools}`

**Comment by fulls1z3** [comment]
@ChrisTarasovs that was done
