### ISSUE TITLE
how to get location with universal

### ISSUE THREAD

**Issue by theomathieubhvr** [fulls1z3/universal#19]
Hey,

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[x] feature request
```

**What is the motivation / use case for changing the behavior?**
I am creating a white label website on which the content shown is dependant from the url used by my users. I cannot use window.location as it is not available server side.

* **Angular version:** 4.1.0

I would be pleased to help you implement this, but do you have any lead on how to do it ?

Thanks !!

PS: This topic seems interesting : http://stackoverflow.com/questions/43403649/how-to-get-full-base-url-including-server-port-and-protocol-in-angular-univer

**Comment by fulls1z3** [comment]
Currently not, but I'll have a look at this probably in the weekend.

**Comment by Gbuomprisco** [comment]
@theomathieubhvr, I am not totally aware of your specific case, but can't (and shouldn't?) the router handle that?

**Comment by theomathieubhvr** [comment]
@Gbuomprisco I'm trying to get the domain of the website I visit.

I tried to do this 
`console.warn((router as any).location._platformStrategy._platformLocation.location);` with no luck server-side.

**Comment by fulls1z3** [comment]
Well, I can suggest you a simple workaround to retrieve that value using [ngx-meta](https://github.com/ngx-meta/core).

There's the [`applicationUrl` parameter](https://github.com/ng-seed/universal/blob/master/src/client/assets/config.json#L4) in `config.json`, which is passed to `MetaStaticLoader` on [app.module](https://github.com/ng-seed/universal/blob/master/src/client/app/app.module.ts#L41). This value is rendered on the page as the `og:url` (`<meta property="og:url" content="http://yourwebsite.com/current_route">`).

You can always access the contents of `og:url` meta tag through the DOM, and then split the value using the slashes.

**Comment by theomathieubhvr** [comment]
Cool ! Thanks

**Comment by theomathieubhvr** [comment]
Ok sorry but I checked and appplicationUrl parameter is very much static.

Maybe I haven't been clear, I will try to reexplain.

Assuming I have a news website with two categories, Politics and Economics. I want to offer http://politics.website.com and http://economics.website.com as urls that my user can go to.

These with ONE repository, yours. I want to know which user is on which website.

Is there any way to do this ?


Thanks :)

**Comment by theomathieubhvr** [comment]
Hi,

I am sorry to bother you with this, but is there any way to do this ? I would be pleased to help implement this.

Thanks !

**Comment by theomathieubhvr** [comment]
OK i managed to do it !

I can make a Pull request if needed (but I think this is too specific).

To sum up how I did, I created a custom OriginService for server (for browser I just set origin to window.location.origin).

```typescript
import { Injectable, Inject } from '@angular/core';
import { Request } from 'express';
import { REQUEST } from '@nguniversal/express-engine/tokens';

@Injectable()
export class OriginService {
  public origin: string;

  constructor(@Inject(REQUEST) private request: Request) {
    this.origin = request.hostname;
  }
}

```

**Comment by mohitkadelongraph** [comment]
@theomathieubhvr I tried you method and I am able to get origin url but its giving an error on browser:

```
Uncaught TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (request.js:31)
var req = Object.create(http.IncomingMessage.prototype)
```

**Comment by theomathieubhvr** [comment]
Have you created a OriginService for the browser too ?

**Comment by dr1ss** [comment]
Any way to achieve this (get the express request object) with @ngx-universal/express-engine please ?
