### ISSUE TITLE
nodemon / npm run serve crashed on rebuild

### ISSUE THREAD

**Issue by ghost** [fulls1z3/universal#20]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**
npm run serve crashes on npm run build:universal-prod or build:universal-dev.

**Expected/desired behavior**
I think it should not crash by rebuilding server.js

**Minimal reproduction of the problem with instructions**

My steps (win10):

    git clone https://github.com/ng-seed/universal.git
    cd universal
    npm install
    npm run build:universal-prod
    npm run serve
    (new console) npm run build:universal-prod

Output:

    D:\path\universal>npm run serve
    
    > @ng-seed/universal@0.4.0-beta.2 serve D:\path\universal
    
    > npm run serve:universal
    
    
    > @ng-seed/universal@0.4.0-beta.2 serve:universal D:\path\universal
    > nodemon ./.server/server.js
    
    [nodemon] 1.11.0
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching: *.*
    [nodemon] starting `node ./.server/server.js`
    Express server listening on http://localhost:8000
    [nodemon] restarting due to changes...
    [nodemon] restarting due to changes...
    [nodemon] restarting due to changes...
    [nodemon] restarting due to changes...
    [nodemon] restarting due to changes...
    [nodemon] restarting due to changes...
    [nodemon] restarting due to changes...
    [nodemon] restarting due to changes...
    [nodemon] starting `node ./.server/server.js`
    module.js:472
        throw err;
        ^
    
    Error: Cannot find module 'D:\path\universal\.server\serv
    er.js'
        at Function.Module._resolveFilename (module.js:470:15)
        at Function.Module._load (module.js:418:25)
        at Module.runMain (module.js:605:10)
        at run (bootstrap_node.js:423:7)
        at startup (bootstrap_node.js:147:9)
        at bootstrap_node.js:538:3
    [nodemon] app crashed - waiting for file changes before starting...

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Win 2012R2, NodeJS 7, current repo

* **Angular version:** 2.0.X
4.1 as in this repo.

* **Browser:** 
Console.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by fulls1z3** [comment]
@ortreum title says everything, it's all about nodemon. You can modify the package.json to force use your project using another tool than `nodemon`.

**Comment by ghost** [comment]
Hello,

@fulls1z3 fulls1z3 then please use a **working** version of nodemon in your package.json because I expect a usable version if I clone this project. I'm not that deep into this subject and can't just "use another tool".

Michael
