### ISSUE TITLE
rollup for optimization of the scripts

### ISSUE THREAD

**Issue by vlados** [fulls1z3/universal#201]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[x] Feature request
[ ] Documentation issue or request
```
I think it will be nice to optimize the build size of the files by integration of rollup.js

**Comment by fulls1z3** [comment]
@vlados that's a killer idea actually, I'll have a look on it after upgrading to ng5.

**Comment by vlados** [comment]
Let's bring it to life :) I cannot do it by myself only but with help ..

**Comment by fulls1z3** [comment]
@vlados that's not quite easy as it seems, there're some points to be cleared first. Although not easy, I'll find a way to realize this :smile:

**Comment by vlados** [comment]
I know it's not but together we can do it :) This is the point of the community

**Comment by fulls1z3** [comment]
@vlados I'm closing this in favor of `sideEffects` feature of webpack 4 #344
