### ISSUE TITLE
no ResourceLoader implementation has been provided

### ISSUE THREAD

**Issue by paulogr** [fulls1z3/universal#21]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**

Got this error when running server
```Error: No ResourceLoader implementation has been provided. Can't read the url "../../assets/colors"```

I have some sass files using `@import`

**Expected/desired behavior**

No error at all

**Minimal reproduction of the problem with instructions**

Just add a scss file and trying to import another scss file.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.1.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript 2.3.2 | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =  7.6.0

Thank you and feel free to ask any further question.

**Comment by rahulbpatel** [comment]
I am running into the same thing.  I am trying to import Bootstrap via the `app.component.scss` file:

```
$icon-font-path: '~bootstrap-sass/assets/fonts/bootstrap/';
@import "~bootstrap-sass/assets/stylesheets/bootstrap";
```

**Comment by rahulbpatel** [comment]
Actually my issue might be unrelated, I just realized I was missing the `bootstrap-sass` package.  I added it and am running into other issues.  Will report back what I find out.

**Comment by rahulbpatel** [comment]
I think that fixed my issue.  @paulogr might want to check that file `"../../assets/colors"` actually exists

**Comment by ennyta** [comment]
I am getting the same error. Any ideas? File is there.

**Comment by ysus** [comment]
i can resolve the issue  that i have but with font-aweson, basically is the same configuration for both:
`{
        test: /\.scss$/,
        use: [{
          loader: "to-string-loader"
        }, {
          loader: "css-loader"
          }
        }, {
          loader: "resolve-url-loader"
        }, {
          loader: "sass-loader", options: {
            sourceMap: true,
            data: '@import "styles";',
            includePaths: [
              DIR
            ]
          }
        }
        ]
      },
      {
        test: /\.(jpe|jpg|woff|woff2|eot|ttf|svg)(\?.*$|$)/,
        use: [{
          loader: "file-loader"
        }]
      }`

DIR // const DIR = join(process.cwd(), 'src', 'styles');

inside the style folder i have  a file called 
styles.scss 

@import 'variables';
@import '../../node_modules/font-awesome/scss/font-awesome';
@import 'global';

inside _varibales.scss 
 $fa-font-path: "../../node_modules/font-awesome/fonts";

repo: https://github.com/FrozenPandaz/ng-universal-demo

**Comment by ennyta** [comment]
I managed to fix it.
In webpack.common.js add this part:
   {
        test: /\.scss$/,
        exclude: /node_modules/,
        loaders: ['raw-loader', 'sass-loader'] // sass-loader not scss-loader
      }

and remove scss from this part:
{
        test: /\.(**scss**|html|png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/,
        use: 'raw-loader'
      }

That enables @imports in sass to be resolved and compiled.

**Comment by mohitkadelongraph** [comment]
@ennyta 
Where should we write this - 
{
test: /.scss$/,
exclude: /node_modules/,
loaders: ['raw-loader', 'sass-loader'] // sass-loader not scss-loader
}
in serverConfig or in browserConfig?
If in browserConfig then do we need to remove pre-defined scss rules?

**Comment by ysus** [comment]
In webpack.common.js

**Comment by fulls1z3** [comment]
@paulogr @rahulbpatel @ennyta @mohitkadelongraph @ysus I was able to reproduce this error, and am going to push a fix within a couple of hours, so stay tuned guys.
