### ISSUE TITLE
Import module only if is browser

### ISSUE THREAD

**Issue by vlados** [fulls1z3/universal#227]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[x] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[x] Documentation issue or request
```
If I have a module that imports module that is not compatible with server side rendering (for example uses window) how I can check if is browser before I declare @NgModule?

**Comment by fulls1z3** [comment]
@vlados please have a look at https://github.com/ng-seed/universal/blob/master/src/client/app/components/layout/main.component.ts#L13.

You will find the implementation of `isBrowser` flag on the component code. Then go to the tempate, and you will notice the `isBrowser` flag in a `ngIf` statement. This way, you might avoid use of non-universal compliant statements.
