### ISSUE TITLE
upgrade to version Angular 5

### ISSUE THREAD

**Issue by maks-potter** [fulls1z3/universal#241]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[x] Feature request
[ ] Documentation issue or request
```

**Expected/desired behavior**
Will you upgrade to version Angular 5 or сan't wait for the update?

**Comment by sarfarazansari** [comment]
@makspotter I've updated this seed to Angular 5.
this Seed has so many issues while updating to Angular 5.
I ended up with build issues.
can't build with `stage` or `prod` now.
here is my updated package.json file.
`"dependencies": {
    "@angular/animations": "5.0.4",
    "@angular/cdk": "5.0.0-rc.2",
    "@angular/common": "5.0.4",
    "@angular/core": "5.0.4",
    "@angular/flex-layout": "2.0.0-beta.10-4905443",
    "@angular/forms": "5.0.4",
    "@angular/http": "5.0.4",
    "@angular/material": "5.0.0-rc.2",
    "@angular/platform-browser": "5.0.4",
    "@angular/platform-browser-dynamic": "5.0.4",
    "@angular/platform-server": "5.0.4",
    "@angular/router": "5.0.4",
    "@angularclass/bootloader": "1.0.1",
    "@nguniversal/express-engine": "5.0.0-beta.5",
    "@ngx-auth/core": "4.1.0",
    "@ngx-cache/core": "4.1.0",
    "@ngx-cache/fs-storage": "4.0.1",
    "@ngx-cache/platform-browser": "4.0.1",
    "@ngx-cache/platform-server": "4.0.1",
    "@ngx-config/core": "4.0.1",
    "@ngx-config/fs-loader": "4.0.1",
    "@ngx-config/http-loader": "4.0.1",
    "@ngx-config/merge-loader": "4.0.1",
    "@ngx-meta/core": "4.0.1",
    "@ngx-translate/core": "9.0.1",
    "@ngx-translate/http-loader": "2.0.0",
    "@ngx-universal/config-loader": "4.0.1",
    "@ngx-universal/state-transfer": "4.0.1",
    "@ngx-universal/translate-loader": "4.0.1",
    "body-parser": "1.16.8",
    "compression": "1.7.1",
    "core-js": "2.5.1",
    "debug": "3.1.0",
    "express": "4.16.2",
    "hammerjs": "2.0.8",
    "lodash": "4.17.4",
    "morgan": "1.9.0",
    "ngx-perfect-scrollbar": "5.0.5",
    "node-sass": "4.7.2",
    "reflect-metadata": "^0.1.10",
    "rxjs": "5.5.2",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@angular/compiler": "5.0.4",
    "@angular/compiler-cli": "5.0.4",
    "@compodoc/compodoc": "1.0.4",
    "@ngtools/webpack": "^1.8.5",
    "@types/express": "4.0.39",
    "@types/jest": "21.1.8",
    "@types/lodash": "4.14.86",
    "@types/nightmare": "1.6.36",
    "@types/node": "8.0.53",
    "add-asset-html-webpack-plugin": "2.1.2",
    "angular-tslint-rules": "1.1.0",
    "angular-webpack-config": "1.4.0",
    "angular2-template-loader": "0.6.2",
    "assets-webpack-plugin": "3.5.1",
    "async": "2.6.0",
    "autoprefixer": "7.1.6",
    "awesome-typescript-loader": "3.4.1",
    "codelyzer": "4.0.1",
    "colorguard": "1.2.0",
    "concurrently": "3.5.1",
    "copy-webpack-plugin": "4.2.3",
    "css-loader": "0.28.7",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "1.1.5",
    "gulp": "github:gulpjs/gulp#4.0",
    "gulp-changed": "3.1.1",
    "gulp-debug": "3.1.0",
    "gulp-exec": "2.1.3",
    "gulp-ignore": "2.0.2",
    "gulp-load-plugins": "1.5.0",
    "gulp-postcss": "7.0.0",
    "gulp-replace": "0.6.1",
    "gulp-sass": "3.1.0",
    "gulp-sass-lint": "1.3.4",
    "gulp-sourcemaps": "2.6.1",
    "gulp-tslint": "8.1.2",
    "hard-source-webpack-plugin": "0.4.11",
    "html-elements-webpack-plugin": "1.0.1",
    "html-loader": "0.5.1",
    "html-webpack-plugin": "2.30.1",
    "jasmine-marbles": "0.2.0",
    "jest": "21.2.1",
    "jest-junit-reporter": "1.1.0",
    "jest-preset-angular": "4.0.1",
    "json-loader": "0.5.7",
    "lazypipe": "1.0.1",
    "ng-router-loader": "2.1.0",
    "nightmare": "2.10.0",
    "nodemon": "1.12.1",
    "optimize-js-plugin": "0.0.4",
    "postcss-loader": "2.0.9",
    "postcss-reporter": "5.0.0",
    "postcss-scss": "1.0.2",
    "raw-loader": "0.5.1",
    "rimraf": "2.6.2",
    "sass-loader": "6.0.6",
    "script-ext-html-webpack-plugin": "1.8.8",
    "standard-version": "4.2.0",
    "style-loader": "0.19.0",
    "stylefmt": "6.0.0",
    "stylefmt-loader": "1.2.3",
    "stylelint": "8.3.1",
    "stylelint-config-standard": "18.0.0",
    "to-string-loader": "1.1.5",
    "tslib": "1.8.0",
    "tslint": "5.8.0",
    "tslint-loader": "3.5.3",
    "typescript": "2.6.2",
    "uglifyjs-webpack-plugin": "1.1.2",
    "webpack": "3.9.1",
    "webpack-dev-middleware": "1.12.2",
    "webpack-dll-bundles-plugin": "1.0.0-beta.5",
    "webpack-hot-middleware": "2.21.0",
    "webpack-merge": "4.1.1"
  },
  "greenkeeper": {
    "ignore": [
      "@ngx-universal/express-engine",
      "@ngx-translate/core",
      "@ngx-translate/http-loader",
      "@types/lodash",
      "supports-color",
      "angular2-template-loader"
    ]
  }`

**Comment by maks-potter** [comment]
@sarfarazansari I think it's a not best way for update because ng-seed using many dependencies some other packages from @fulls1z3 which using dependencies from angular 4x version, for example, @ngx-config/http-loader use Http module which was removed in Angular 5. 
I think we must wait when @fulls1z3 will start update other dependent packages to Angular 5 or we must move project to official ng-cli but the second way is more complicated

**Comment by fulls1z3** [comment]
@sarfarazansari @makspotter guys it all depends to the packages (*ngx-config. ngx-meta, etc.*) that this seed depends to. It's already on our roadmap but it seems I'll need a couple of more weeks to handle this upgrade on all dependent packages - due to the limited free time that I have currently.

Honestly, I need this upgrade on the commercial projects we're actively developing in our company, so the current situation won't last long.

**Comment by sarfarazansari** [comment]
@makspotter I know that Seed has dependencies on the 4x version.
But I updated packages according to there dependencies.
and I got succeeded and everything is working fine.
except `prod` and `stage` build in both mode (universal | lean)

**Comment by slavpilus** [comment]
@fulls1z3 any update on when we can expect the Angular 5 migration?

**Comment by fulls1z3** [comment]
@slavP I'm still working on a very dense schedule. Depending on the results on the upcoming weeks, I'm going to to either take required actions for the dependencies, or at least prepare a roadmap.

So that we can clearly see what steps to follow. Meanwhile, contributions would take place as everything is going to be planned.

**Comment by sarfarazansari** [comment]
@fulls1z3 I've tried to update this seed to Angular 5.
but Ended with so many issues and errors.
most of them are regarding web pack and some universal gotchas.

**Comment by fulls1z3** [comment]
@sarfarazansari @slavP @makspotter I'm glad to say that in a few hours the migration will be done :)

**Comment by vlados** [comment]
@fulls1z3 Where we can test it? Are you merging it into master repo?

**Comment by fulls1z3** [comment]
@vlados yeah friend, I merged it into master and using it as upstream on my commercial projects. Results are hot, and I honestly loved the ng5.

Meanwhile, there're still issues with app flickering (rendering twice on server and browser passes). Any help is highly appreciated.
