### ISSUE TITLE
add proxy conf

### ISSUE THREAD

**Issue by rem42** [fulls1z3/universal#244]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[x] Feature request
[ ] Documentation issue or request
```

**Expected/desired behavior**
Add the proxy conf for the webpack configuration file. To use it like we can do in angular-cli

Example : 

`{
  "/api": {
    "target": "http://localhost:8000",
    "secure": false,
    "changeOrigin": true
  }
}`

I already try to add in build-config.json this : 

`  "proxy": {
    "/api": {
      "target": "https://localhost:8000",
      "secure": false
    }
  },`

But not working.

**What is the motivation / use case for changing the behavior?**
In order to use an API

Sorry for my bad english, i'm french and this is my first issue.

**Comment by shayangz** [comment]
+1

**Comment by codex-corp** [comment]
Here a solution,
https://github.com/chimurai/http-proxy-middleware/blob/master/README.md#http-proxy-middleware-options
```

var express = require('express');
var proxy = require('http-proxy-middleware');

var app = express();

app.use('/api', proxy({target: 'http://www.example.org', changeOrigin: true}));
app.listen(3000);

// http://localhost:3000/api/foo/bar -> http://www.example.org/api/foo/bar
```

![image](https://user-images.githubusercontent.com/775654/45119951-7ce51000-b165-11e8-8455-739db6384b11.png)
