### ISSUE TITLE
mapping sass to source file instead of compiled style.bundle.js

### ISSUE THREAD

**Issue by NathanBraslavski** [fulls1z3/universal#287]
**I'm submitting a ...**
```
[ X ] Support request
```

**Current behavior**
In Elements > Style debug view (Developer Tools) all the styling are mapped to the compiled file, in chrome represented as the source of the css in <style>...</style>
I tried to change the values of the source map in the `build-config.json`
according to [devtool doc](https://webpack.js.org/configuration/devtool/)
```
"webpack": {
    "devtool": {
      "DEV": "cheap-module-source-map",
```
But it didn't have any effect on the style mapping.

**Expected/desired behavior**
I would like to get the reference to the original source file for each style (e.g the scss mapping)
for more info read: [using source maps debug sass chrome](https://www.sitepoint.com/using-source-maps-debug-sass-chrome/)

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Will make debugging styles much easier and faster 

* **Browser:**
- [x ] Chrome (desktop) version 62

* **For Tooling issues:**
- Node version: 7.0.0
- Platform: Linux, Windows

* Others:

**Comment by fulls1z3** [comment]
#507
