### ISSUE TITLE
production build issue `Uncaught Error: No NgModule metadata found for 't'.`

### ISSUE THREAD

**Issue by ChrisDalley** [fulls1z3/universal#29]
```
[x] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**
It seems to be that recently an npm dependency has been updated which causes silent build issues for production builds, both build:universal-prod and build:spa-prod . Previously everything has been working fine as for production builds but sometime in the last week these issues have arose. 

Webpack itself gives no errors during the build but no css file is generated in the public folder. 
The app will run but the css styles for the main app bundle do not show (lazy loaded modules still seem to display css for their components). 

An error gets generated in the console 
```
Uncaught Error: No NgModule metadata found for 't'.
    at t.resolve (app.3be5665….bundle.js:1)
    at t.getNgModuleMetadata (app.3be5665….bundle.js:1)
    at t._loadModules (app.3be5665….bundle.js:1)
    at t._compileModuleAndComponents (app.3be5665….bundle.js:1)
    at t.compileModuleAsync (app.3be5665….bundle.js:1)
    at e._bootstrapModuleWithZone (app.3be5665….bundle.js:1)
    at e.bootstrapModule (app.3be5665….bundle.js:1)
    at r (app.3be5665….bundle.js:1)
    at r (app.3be5665….bundle.js:1)
    at Object.163 (app.3be5665….bundle.js:1)
```

I attempted to trace this through but no luck as of yet. I will take more of a look at the production webkit builds over the next day or two and see if I can isolate the issue. In the mean time it would be great if anyone else could reproduce. 

**Expected/desired behavior**
Prod Build should compile the production bundles including CSS with no errors. 

**Minimal reproduction of the problem with instructions**
I have tried with existing projects using this repository as well as cloning a new repo from this one.

Clone this repository locally
Run 
```
npm install
npm run build:universal-prod
npm run serve:universal
```
If you have an existing code base using this repository 
```
rm -rf node_modules
npm cache clean
npm install
npm run build:universal-prod
npm run serve:universal
```

**Comment by fulls1z3** [comment]
@ChrisDalley after upgrading to `Node.js v8` and `TypeScript v2.4.1` I'm also getting errors, however they're connected with `rxjs`.

The reason that the production builds resulting with failure is because the `no-errors` webpack plugin (*prevents the build to be complete in case of any errors*).

I'm currently working on a breaking change for the webpack configuration, and I think we'll find a solution to these issues. Meanwhile ping me when you face something useful.

**Comment by fulls1z3** [comment]
@ChrisDalley now I reproduced this error, I think things will become easier now 👍

**Comment by fulls1z3** [comment]
@ChrisDalley can you please share the exact @angular, typescript, @ngtools/webpack and rxjs versions? That might be useful.

**Comment by fulls1z3** [comment]
@ChrisDalley I'll also need the exact webpack version that you're using.

**Comment by ChrisDalley** [comment]
@fulls1z3 Here are the versions
@ angular/core@4.1.3
rxjs@5.4.1
typescript@2.3.4
webpack@2.6.1

**Comment by fulls1z3** [comment]
@ChrisDalley I found it! It's all about `@ngtools/webpack`. Please let me know which version of `@ngtools/webpack` is at your system (*better have a check looking at the package.json in the node_modules folder*). Meanwhile, I'll try to find out the maximum working version of `@ngtools/webpack`.

**Comment by fulls1z3** [comment]
@ChrisDalley I want to thank you specially for pointing out such an issue, the information you provided greatly helped the solution 👍

**Comment by ChrisDalley** [comment]
@fulls1z3 - Thanks for taking a look so fast! Its all about what package though sorry? It didnt show in your last message!

**Comment by fulls1z3** [comment]
@ChrisDalley I edited the post, `@ngtools/webpack` appears now :smile:

**Comment by ChrisDalley** [comment]
Oh great! Im currently on version
```
@ngtools/webpack@1.4.2
```

**Comment by fulls1z3** [comment]
Try to switch to v1.3.3 now if things are urgent. Further versions do not work. I'm not surprised, `@angular/cli` still seems unreliable.

I'll update the repo within a few hours if things are not urgent for you. For now, use this dude:

#### package.json
```
"@ngtools/webpack": "1.3.3",
```

**Comment by ChrisDalley** [comment]
@fulls1z3 thats done the job - cheers for the help! Great work with the repo btw 😄

**Comment by fulls1z3** [comment]
@ChrisDalley thanks too, and it would be nice if you can make a favor: Can you please post this issue (*meanwhile I'm working for a permanent solution over here*), with same details at the `@angular/cli` repository - mentioning `@ngtools/webpack` with working and non-working versions?

It would definitely help the Angular team to reconsider their strategy and solve this issue on the upcoming releases of `@ngtools/webpack`. you can refer to this issue and my name too, no problem.

Cheers 👍

**Comment by fulls1z3** [comment]
@ChrisDalley thanks mate, you saved the day and you'll save the future too 👍

**Comment by fulls1z3** [comment]
@ChrisDalley this has been solved using the latest **@ngtools/webpack**.

**Comment by ChrisDalley** [comment]
@fulls1z3 - Thanks for the update :)
