### ISSUE TITLE
vague error message on `universal-prod`

### ISSUE THREAD

**Issue by ld-gary** [fulls1z3/universal#296]
**I'm submitting a ...**
```
[ ] Regression
[ ] Bug report
[x] Support request
[ ] Feature request
[ ] Documentation issue or request
```

**Current behavior**
Unspecified error in unspecified (and destroyed) file on production build

**Expected/desired behavior**
Some indication as to where the error occurs within the codebase

**What is the motivation / use case for changing the behavior?**

**Environment**
* **Angular version:** 4.4.6

* **For Tooling issues:**
- Node version: 7.4.0 (also 6.9.5 locally, I know, I need to update...)
- Platform: Mac locally, Ubuntu 14 Server for production

I'm running in to a vague error when running build:universal-prod, it occurs during the 'bundle:universal-browser-prod' task and ultimately leads to a full build failure.

I suspect this error may be coming from the uglify plugin based on a look through the issues but can't be sure. What I really want to know is does anybody have a good (quick if possible) strategy for tracking down the source of a build error that reads like the following...

    Error: Unexpected token (975:118825)
    (1) error(s) total.

This is obviously really vague but also the compiled output is subsequently discarded which makes locating the line (975 in this case) impossible to check. This leaves me with the task of debugging old school style by removing batches of code from all of the latest changed files (quite a few in this case) and running production builds until the error disappears, which hurts my soul! I haven't implemented any test suites, not sure they would catch this anyway, but I acknowledge the need to do this moving forward in my own work.

If anyone has any wisdom (including outright criticism) to send my way regarding tackling this I would love to hear from you!

**Comment by fulls1z3** [comment]
I think it's caused by `uglify-webpack-plugin`, try to update to the latest `angular-webpack-config` where the uglification is (*temporarily*) disabled.

Also you can follow #284 for the latest changes on this functionality.

**Comment by ld-gary** [comment]
Hey, ok cool will keep an eye on that thread. Just FYI though, my project is pretty large and was started way before the release of Angular 5, thus, I can't easily migrate to 5 given current work load. Updating to the latest angular-webpack-config isn't an option for me right now so I'm stuck with none prod builds.

**Comment by ld-gary** [comment]
I updated to the latest version that includes Angular 5 and the latest `angular webpack-config` in which you have commented out the uglify plugin code. Still getting this vague error. I've even deleted most of the components from our app in an attempt to eliminate the error and therefore narrow down the source... no joy.

Only during production build, not caused by uglify. I'm rooting through your config plugin to see what I can glean but this is truly a needle in a haystack. Preventing us from launching our app.

Any ideas at all as to where this could be coming from?

<img width="272" alt="screen shot 2018-01-26 at 10 49 23" src="https://user-images.githubusercontent.com/15818048/35436545-c1df6c02-0286-11e8-9ebe-f429bc703fc8.png">

**Comment by ld-gary** [comment]
Though... I've just cloned a fresh copy of the ng-seed codebase and it built just fine. Really still could be from anywhere including a third party module so I'm still stumped. Sorry to hassle this thread but I'm hacking at this issue alone! I look forward to the day when the thrown error is a little more clear than a puddle of mud...

**Comment by ld-gary** [comment]
Just to finish this thread, it turned out to be an outdated wrapper for a swiper plugin that was causing this. The only real solution was to methodically remove chunks of code or imports and re-build until the error went. If anyone is reading this and having a similar struggle, first, my condolences, second... maybe check through the third party packages you are using and make sure they conform to the standards/conventions of your Angular version. In my case the Swiper wrapper package author had a warning in the readme for the version of the wrapper that my app was pulling in which it was mentioned that it wasn't quite up to date with latest Angular releases. It hadn't caused the error for a good month and a half so not sure how it was ever working, unless I triggered a bug fix update of my Angular version that pushed it out of the swiper wrapper's capabilities.
