### ISSUE TITLE
chat room for talks

### ISSUE THREAD

**Issue by vlados** [fulls1z3/universal#306]
Hi guys,
I've created a chat room where we can discuss or ask our questions and not to flood @fulls1z3 with questions :)

https://gitter.im/ngx-universal/Lobby#

**Comment by fulls1z3** [comment]
@vlados, awesome idea my friend 👍 

however, there was a room which was created ages ago, and i sent invites everyone i could.

here's the link: https://gitter.im/ng-seed-universal/Lobby

**Comment by vlados** [comment]
Put the link in the readme so everyone can know about it ;)
