### ISSUE TITLE
hostListener events aren't firing in universal builds

### ISSUE THREAD

**Issue by JoshElias** [fulls1z3/universal#312]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
```

**Current behavior**

Events like:
```
 @HostListener('document:mousemove', ['$event'])
  onMouseMove(event: any) {
        console.log("mouse move")
  }
    @HostListener('window:mousewheel', ['$event'])
    onMouseWheelChrome(event: any) {
        console.log("scroll")
    }
    @HostListener('window:DOMMouseScroll', ['$event'])
    onMouseWheelFirefox(event: any) {
        console.log("scroll")
    }
    @HostListener('window:onmousewheel', ['$event'])
    onMouseWheelIE(event: any) {
        console.log("scroll")
    }

```

**Expected/desired behavior**

The events should fire

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Environment**
* **Angular version:** X.Y.Z

* **Browser:**
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by vlados** [comment]
@JoshElias: I am using this code and it works with angular 5.2. What version of angular you are using?

    @HostListener('document:keydown.escape', ['$event']) onKeydownHandler(): void {
        this.close();
    }

    @HostListener('click', ['$event']) onClick(evt: MouseEvent): void {
        this.close(evt);
    }

**Comment by JoshElias** [comment]
I'm very sorry but after spending all day digging it was a bad path to my public assets (app bundle) that made it look as if the events weren't firing. 

Thank you very much for the response and I'll close this issue.
