### ISSUE TITLE
importing auth0 breaks universal

### ISSUE THREAD

**Issue by ghost** [fulls1z3/universal#32]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the README and search github for a similar issue or PR before submitting
[x] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```
After importing auth0-js in a component I'm receiving the following error after building and serving via express. SPA mode works fine however. 

**Import**:
`import auth0 from 'auth0-js';`
**Run**: 
npm run build:universal-dev
npm run serve
**Error**:
```
/.server/server.js:134432
var crypto = require('crypto');
             ^
TypeError: require is not a function

```

**Comment by fulls1z3** [comment]
@vanaio it seems like an issue with module resolution. Is it possible for you to share a codepen url, or upload to a repository on github (*so that we'll be able to reproduce the issue and see what's wrong*)?

**Comment by artemsoliar** [comment]
I'm trying to use a preboot js to help manage the transition of state , and I understand require is ignored in source code below (inline.preboot.code.ts)
  ```
const eventRecorderFn = opts.minify ?
    require('../../dist/preboot.min.js') :
    require('../../dist/preboot.js');
```

**Comment by fulls1z3** [comment]
@artemSoliar as a rule of thumb, I avoid using statements with `require` in a TS-environment.
