### ISSUE TITLE
XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by singhmohancs** [fulls1z3/universal#34]
I am using this seed for server side rendering. Everything works perfectly.

Now, Issue occurs when any `node_mode` make a `XMLHttpRequest`. I have used `https://github.com/backand/angular2-sdk` this SDK in an application. This SDK makes an `XMLHttpRequest` to fetch data from the backend.

#### Client side rendering does work perfectly because `XMLHttpRequest` object is available in the browser.

<img width="1229" alt="screen shot 2017-07-12 at 10 15 45 pm" src="https://user-images.githubusercontent.com/283132/28143048-44b9eb30-6781-11e7-91ed-2fe0bfe27e84.png">

**Comment by fulls1z3** [comment]
@singhmohancs as far as i see, the compilation is made using `universal-starter` library. Could you please enrich the issue with more information?
