### ISSUE TITLE
support webpack v4

### ISSUE THREAD

**Issue by johnbendi** [fulls1z3/universal#344]
**I'm submitting a ...**

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [ ] Support request => 
- [x] Feature request
- [ ] Documentation issue or request

**Current behavior**
Currently ng-seed works with webpack v3

**Expected/desired behavior**
I desire for webpack v4 support

**Minimal reproduction of the problem with instructions**
Upgrading to webpack v4 breaks commonsChunkPlugin and some others and obsoletes some other code in this repo

**What is the motivation / use case for changing the behavior?**
Improved application compilation efficiency

**Environment**
* **Angular version:** v5

* **Browser:**
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

* **For Tooling issues:**
- Node version:  v8.9.4
- Platform:  Linux

* Others:

**Comment by fulls1z3** [comment]
@johnbendi all done, enjoy the latest stack 👍
