### ISSUE TITLE
HMR app.scss

### ISSUE THREAD

**Issue by theomathieubhvr** [fulls1z3/universal#35]
The sass files in assets/sass are not live reloaded when a changes occured.

I'll try to fix soon this when I have time available.
My PR might be in angular-webpack-config repo.

**Comment by fulls1z3** [comment]
@theomathieubhvr thank you very much for finding out this, seems like this feature need some enhancements.

Meanwhile I'll invite you as a contibutor to this project as well as `angular-webpack-config` project. And I will do the same if you're interested in others (*almost all dependencies with `ngx-` prefix*).

**Comment by theomathieubhvr** [comment]
Ok, I'll do it ASAP. I've succeeded in doing this when you didn't use angular-webpack-config. I should be able to make it working with angular-webpack-config.

**Comment by fulls1z3** [comment]
I know that `angular-webpack-config` seems to make things a little more complicated, but I'm depending on the same config on 10+ projects. Every time this config needs an update I had to make the changes on all those projects (*which leads to mistakes, issues, etc.*).

With `angular-webpack-config` changes are more or less centralized, increasing the version number works like a charm in most cases :smile:

**Comment by theomathieubhvr** [comment]
Done with https://github.com/fulls1z3/angular-webpack-config/pull/1
