### ISSUE TITLE
can't add assets

### ISSUE THREAD

**Issue by ahmed-anas** [fulls1z3/universal#36]
**I'm submitting a ...** 
```
[x] bug report => check the README and search github for a similar issue or PR before submitting
[x] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**
adding `<img src="assets/pic.jpg" />` to `app.component.html` (and a pic.jpg in the assets folder) gives the error: `Can't resolve './assets/pic.jpg'`

changing the path of the asset to relative, i.e making it `<img src="../assets/pic.jpg" />` gives the error: ` Error: Path variable [chunkhash] not implemented in this context: assets/pic.[chunkhash].jpg`. Assets should not be relative so adding the `../` shouldn't work in any case.

I run using: `npm run build:universal-prod; npm run serve;`
**Expected/desired behavior**

It should work. Or perhaps this is configured to work with different sort of paths? If so, please advice.

**Please tell us about your environment:**
Windows 10 

* **Browser:** all

* **Quick Solution: ** changing `chunkhash` to `hash` in the `webpack.common.js` file seems to fix this error though I'm not sure what complications that might have.  Although the path would need to be relative to the current location, and ideally we should just be able to do `assets/pic.jpg` or something of the sort.

**Comment by artemsoliar** [comment]
I use like this` <img src="/assets/pic.jpg" />`

**Comment by ahmed-anas** [comment]
@artemSoliar In this scenario webpack doesn't add the image to the generated output public folder and I have 404 errors.

I'm using the bare `ng-seed/universal` master branch for testing this. The steps I do are

* insert a `pic.jpg` file in assets 
* add `<img src="/assets/pic.jpg" />" in `app.component.html`
* run `npm run build:universal-prod`
* run `npm run serve`

**Comment by artemsoliar** [comment]
in webpack.config.js file add like this
```
 new copyWebpackPlugin([
     {
          from: `${root(settings.paths.src.client.assets.root)}/pic.jpg`,
          to: './pic.jpg'
        },]
```
more https://github.com/kevlened/copy-webpack-plugin

**Comment by ahmed-anas** [comment]
@artimSoliar thanks, that helped. Not an ideal solution but good enough.

**Comment by theomathieubhvr** [comment]
You can also add folders path to copy directories:

https://github.com/ng-seed/universal/blob/master/config/webpack.config.js#L26

**Comment by fulls1z3** [comment]
@ahmed-anas, @artemSoliar, @theomathieubhvr  done 👍
