### ISSUE TITLE
absolute vs relative paths within templates using publicPaths

### ISSUE THREAD

**Issue by kirilogan** [fulls1z3/universal#368]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[x ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
```

**Current behavior**
Although another issue was closed stating that we could set the **publicPaths** to **"/assets/"**, but it still does not allow for absolute paths for use in templates ex. using /assets/img/logo.png. Although no errors are shown, the "logo.png" files does not get placed into the public/assets folder.

`  "publicPaths": {
    "assets": "/assets/",
    "images": "img",
    "fonts": "fonts"
  },`

**Expected/desired behavior**
To be able to use "/assets/img/logo.png" when publicPaths.assets = "/assets/"

**Minimal reproduction of the problem with instructions**
1. clone a vanilla instance of repo
2. add a image named logo.png to src/client/assets/img/
3. modify header.component.html to include `<img src="/assets/img/logo.png" />`
4. modify the "publicPaths" within build-config.json to:
`  "publicPaths": {
    "assets": "/assets/",
    "images": "img",
    "fonts": "fonts"
  },`

**What is the motivation / use case for changing the behavior?**
to be able to use absolute paths within templates

**Environment**
* **Angular version:** 6.0.0-beta.6

* **Browser:**
- [x ] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

* **For Tooling issues:**
- Node version: 8.11.1
- Platform:  Windows

* Others:
all vanilla clone as instructed on the main readme

**Comment by fulls1z3** [comment]
#507
