### ISSUE TITLE
hmr not refreshing

### ISSUE THREAD

**Issue by vlados** [fulls1z3/universal#369]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
```
When stylelint throw a warning in the console it's not reloading the new changes. How I can make it show a warning but still refresh the new changes?

**Comment by fulls1z3** [comment]
@vlados well I can answer this just after I've finished with webpack4 / rxjs6 / angular6 upgrade.

If things go alright, the update will happen tonight 👍

**Comment by fulls1z3** [comment]
@vlados all done, enjoy the latest stack 👍
