### ISSUE TITLE
unable to update dependacies

### ISSUE THREAD

**Issue by vlados** [fulls1z3/universal#37]
```
[x] bug report
```

**Current behavior**
When run `npm update` I am getting
```
Vladislavs-MacBook-Pro:udoma personal$ npm upgrade
@ng-seed/universal@0.4.0-beta.2 /Users/personal/code/udoma
├── UNMET PEER DEPENDENCY @ngx-cache/core@0.4.0-beta.2
├── gulp@4.0.0-alpha.2  (git://github.com/gulpjs/gulp.git#38246c3f8b6dbb8d4ef657183e92d90c8299e22f)
├── uglify-js@2.8.22  (git://github.com/mishoo/UglifyJS2.git#278577f3cb75e72320564805ee91be63e5f9c806)
└── UNMET PEER DEPENDENCY webpack@3.3.0

npm WARN @ngtools/webpack@1.3.3 requires a peer of webpack@^2.2.0 but none was installed.
npm WARN @ngx-cache/fs-storage@0.4.0-beta.2 requires a peer of @ngx-cache/core@0.4.0-beta.1 but none was installed.
npm WARN extract-text-webpack-plugin@2.1.2 requires a peer of webpack@^2.2.0 but none was installed.
```
**Expected/desired behavior**
Npm update successful

**Minimal reproduction of the problem with instructions**
1. Clone repo
2. Run `npm update`

**What is the motivation / use case for changing the behavior?**
So I can use the repo with the latest versions of node modules, install other node modules

**Please tell us about your environment:**
OSX

**Node (for AoT issues):** `node --version` =   v6.10.3

**Comment by fulls1z3** [comment]
@vlados actually `npm` updates the deps, but displays a warning if there're any unmet peer dependencies. So, things should work fine (*because higher versions of those deps are already included in `node_modules` directory*).
