### ISSUE TITLE
production mode build fails when using packages with scss and @import

### ISSUE THREAD

**Issue by ahmed-anas** [fulls1z3/universal#38]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**
using a package like [ngx-chips ](https://github.com/Gbuomprisco/ngx-chips) with `scss` files having `@import` gives an error `unexpected character @` only when building in production mode
**Expected/desired behavior**
should work

**Minimal reproduction of the problem with instructions**

* install ngx-chips view `npm install ngx-chips -S`
* include the minimal template in `home.component.ts`: `<tag-input [(ngModel)]='tags'></tag-input>`
* add an `tags` array to `home.component.ts`
* include `TagInputModule` to `home.module.ts` from `ngx-chips`
* build in `prod` mode with either `npm run build:spa-prod` or `npm run build:universal-prod`

**Please tell us about your environment:**
vs code, windows 10

* **Browser:** all

 
* **Node (for AoT issues):** `node --version` =   7.8.0

**Comment by fulls1z3** [comment]
@ahmed-anas I'll have a look on this on the first opportunity, and many thanks for your contributions 👍

**Comment by fulls1z3** [comment]
@ahmed-anas done 👍
