### ISSUE TITLE
error running build tasks

### ISSUE THREAD

**Issue by hadirsa** [fulls1z3/universal#391]
**I'm submitting a  bug report. I try to run any of build goals and at the end i get errors.

For example for `build:universal-prod` and build:spa-prod i have faced the below error  :

```
...
[09:17:59] Starting 'build:universal-prod'...
[09:17:59] Starting 'bundle:universal-browser-prod'...
(node:15988) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:15988) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
[09:18:04] 'bundle:universal-browser-prod' errored after 4.94 s
[09:18:04] TypeError: Cannot read property 'outputOptions' of undefine
...
```
for `build:universal-dev` i have faced the below error:
 
```
Error: ./src/server/server.ts
Module build failed: Error: Angular Compiler was detected but it was an instance of the wrong class.
This likely means you have several @ngtools/webpack packages installed. You can check this with `npm ls @ngtools/webpack`, and then remove the extra copies.
    at Object.ngcLoader (J:\Java\front\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\loader.ts:39:11)

    (1) error(s) total.
``` 

``` 
[* ] Bug report 
```
 
* **For Tooling issues:**
- Node version: **v8.9.4** 
- Platform: Windows  

Any idea about these errors?

**Comment by fulls1z3** [comment]
@hadirsa just run both command just after a successful execution of `yarn`.

Which tool did you use to install the deps? NPM or YARN?

**Comment by hadirsa** [comment]
@fulls1z3, i use` yarn`,  also i tried to install deps with `npm` and  run build:* , i got the same error. 

I tried to run `build:*` with yarn and npm and only `build:spa-dev` works fine.

I run these goals right after `yarn `or `npm install`, am i doing wrong?

**Comment by fulls1z3** [comment]
@hadirsa it's best to clone a fresh version from the repository and just execute these commands (as i've succeeded here):

* `git clone https://github.com/ng-seed/universal`
* `yarn`
* `npm run build:universal-dev`
or
* `npm run build:universal-prod`

**Comment by hadirsa** [comment]
@fulls1z3 , i did as you said but the errors were  same as i said before but **with npm install every thing works fine**. Is there any issue with yarn? Didn't you face any issues with yarn?

**Comment by fulls1z3** [comment]
@hadirsa actually I just had time to review issues, and i had some other issues with yarn. As a result, I deleted it totally and installed a new version. Now, things are more or less fine.
