### ISSUE TITLE
background images break source

### ISSUE THREAD

**Issue by zvanagas** [fulls1z3/universal#40]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**
If background with an image is added to any sass file, source code breaks

**Expected/desired behavior**
Source code should be generated with background image assets

**Minimal reproduction of the problem with instructions**
1. Add background-image with an url to sass file
2. Inspect source code

* **Angular version:** 4.1.3 (I am using Angular-webpack-config)

* **Browser:** Chrome 59

**Comment by artemsoliar** [comment]
use url like this `background-image: url(/assets/pic.jpg);`
look https://github.com/ng-seed/universal/issues/36

**Comment by theomathieubhvr** [comment]
Closing in favor of #36
