### ISSUE TITLE
rimraf is not recognized as an internal or external command

### ISSUE THREAD

**Issue by createbuildship** [fulls1z3/universal#408]
'rimraf' is not recognized as an internal or external command,
Do you need to do npm i?

**Comment by vlados** [comment]
@frontr-uk read the readme ;)

**Comment by createbuildship** [comment]
i did, can you be more helpful and not expect everyone to understand everything on the spot. There people in different levels of coding :)

**Comment by vlados** [comment]
@frontr-uk If you want a proper answer please submit a proper question by using the guidelines
https://github.com/ng-seed/universal/blob/master/CONTRIBUTING.md#submit-issue
