### ISSUE TITLE
remove compiler from AoT client bundle

### ISSUE THREAD

**Issue by andresantos123** [fulls1z3/universal#43]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**
When run "npm run build:universal-prod" the client package contains the `@angular/compiler`

**Expected/desired behavior**
The client package dont need the compiler on AOT compilations

**Minimal reproduction of the problem with instructions**
Use webpack bundle analyzer plugin to check client bundle

**What is the motivation / use case for changing the behavior?**
Remove more them 300kb on client blundle

**Please tell us about your environment:**
Fedor Linux

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

**Comment by fulls1z3** [comment]
@andresantos123 thanks for the idea, I'll try and test this on the first opportunity.

**Comment by andresantos123** [comment]
Hi,
I made a quick test and appears that the AOT is not working. With bundle analyzer, we cant see the ng-factory generated files. Changing the webpack/tsconfig made the bundle generate the compiled files.

**Comment by fulls1z3** [comment]
@andresantos123 actually AoT was working on **@angular** `v4.2.4` and **@ngtools/webpack** `v.1.3.3`; however after the latest PR's their versions have been upgraded and this causes the AoT to be broken.

I'm working on this now, if none works I'll roolback the **@angular** version to `v4.2.4`.

**Comment by fulls1z3** [comment]
@andresantos123 @theomathieubhvr Well, I solved this. Also it fixes the earlier https://github.com/ng-seed/universal/issues/29 and https://github.com/ng-seed/universal/issues/39.

Furthermore, mentioned the solution at https://github.com/angular/angular-cli/issues/6833.

**Comment by fulls1z3** [comment]
@andresantos123 now the AoT got solved, do you have any suggestions on this topic?
@theomathieubhvr I'd like to hear your opinions also.

Also, this might be connected with `@ngx-universal/state-transfer` https://github.com/ngx-universal/state-transfer/issues/9

**Comment by andresantos123** [comment]
@fulls1z3 Now AOT is working like a charm! Tried a way to remove the compiler based on another starters without success.
