### ISSUE TITLE
auto restart and rebuild angular universal on save

### ISSUE THREAD

**Issue by ghost** [fulls1z3/universal#438]
I turned my application to angular universal. It's great but I have a problem with developing mode. I need to see my editing result real-time. I need to restart my app on each atrl+s (save) like `build --watch` and `nodmeon`.

My server is Eexpressjs and I'm using the command  `"npm run build:ssr"` after each edit. It takes lots of time!!
How can I do that?

**Comment by fulls1z3** [comment]
@samialmorshedi it writes on readme

**Comment by ghost** [comment]
@fulls1z3  I have read the whole readme file. I did not find that. Could you please help me find it or mention the exact part that I could find it? Thanks a lot.

**Comment by vlados** [comment]
How it is possible? Its here https://github.com/ng-seed/universal#-building
