### ISSUE TITLE
custom index.html head tags from a service during bootstrap

### ISSUE THREAD

**Issue by jrmcdona** [fulls1z3/universal#44]
Hi All,
Do I have the ability to include other custom  Headtags?  For example, I need to make an a service call to a trusted service to get dynamic <script> tags to be inclued in the Head.   It looks like the below code is more for config, but just wonder what I should look into to extend it.  Appreciate any direction on that!

```
<% if (webpackConfig.htmlElements.headTags) { %>
    <%= webpackConfig.htmlElements.headTags %>
    <% } %>
```

Thanks

**Comment by fulls1z3** [comment]
@jrmcdona actually yes, there was a sample implementation of this at the [angular-starter](https://github.com/AngularClass/angular-starter) repository. The same trick would work here, because the webpack config and webpack plugins of this repo were inspired from @AngularClass.
