### ISSUE TITLE
re-group deps

### ISSUE THREAD

**Issue by fulls1z3** [fulls1z3/universal#45]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[X] feature request
```

**Current behavior**
The deps are all in alphabetical order.

**Expected/desired behavior**
They should be re-grouped again (*see #41*).

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by theomathieubhvr** [comment]
I fixed this issue in my last pull request (to avoid a lot of conflicts in package.json).

Not sure it was the best place to do it but it is done! ;)

**Comment by fulls1z3** [comment]
@theomathieubhvr thanks dude, I also made a few last touches and it's done 👍
