### ISSUE TITLE
devtool with development (eval) configs

### ISSUE THREAD

**Issue by ahmed-anas** [fulls1z3/universal#46]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the README and search github for a similar issue or PR before submitting
[ * ] support request => check the README and search github for a similar issue or PR before submitting
[ * ] feature request
```

**Current behavior**
Current we use cheap-module-source-map. When changed to an *eval* dev tool (like cheap-module-eval-source-map)  or one of the 'development' devtools, get the error `Error: HtmlWebpackPlugin: could not load file vendor.dll.js.map`

**Expected/desired behavior**
It should work. 

**Minimal reproduction of the problem with instructions**
change "DEV" devtool (in `build-config.json`) from `cheap-module-source-map` to `cheap-module-eval-source-map` and run the development build

**What is the motivation / use case for changing the behavior?**
To allow for better debugging

**Please tell us about your environment:**
VS code

* **Browser:** all

Unfortunately I'm not an expert with webpack builds. If you can provide some guidance I can work on a pull-request.

**Comment by ahmed-anas** [comment]
Turns out the issue is with my local changes. My bad. Closing.

**Comment by ahmed-anas** [comment]
I believe this might be happening because of a conflict between the style mapping file and app.module mapping file (where both are created as `app.map` but the css map file overwrite the js map file, which I guess is another bug

**Comment by fulls1z3** [comment]
@ahmed-anas I'll try to look at this, but gave the priority to issues with higher priority considering the limited time I've got because of my work schedule.

@theomathieubhvr I'd like to consult you about this too (*I know I asked much nowadays :smile:*)

**Comment by fulls1z3** [comment]
#507
