### ISSUE TITLE
language switching does not work

### ISSUE THREAD

**Issue by ebondu** [fulls1z3/universal#49]
```
[x] bug report 
[ ] support request 
[ ] feature request
```

**Current behavior**

The page content is not updated regarding to the selected language (but the page title does)

**Expected/desired behavior**

The page content should be updated after language changed

**Minimal reproduction of the problem with instructions**
Not working on both living exemple and local 

Thanks.

**Comment by fulls1z3** [comment]
@ebondu it's because the page titles and meta descriptions have been pulled from the language file, but the static content on the components are hard-coded strings.

**Comment by ebondu** [comment]
Sorry about that, I didn't take the time to inspect the code to see messages was hardcoded... I noticed the official angular i18n tool was not part of the project, did you plan to switch to the official tool ?

**Comment by fulls1z3** [comment]
@ebondu it's ok, meanwhile we can't introduce the official i18n tool immediately, still a lot of people depend working with `ngx-translate`.

Furthermore, many libraries depend on `ngx-translate`, so we need to wait them rewritten according to the official angular i18n.

**Comment by ebondu** [comment]
Thanks for your reply. It make sense to wait for a better support of the official i18n in other libs/deps. Any idea about a roadmap for this evol ?

**Comment by fulls1z3** [comment]
@ebondu currently not, we need to see and check Angular 5.0 generally available release first.

**Comment by ebondu** [comment]
Ok thanks, I will keep an eye on the projet. Great job ;)
