### ISSUE TITLE
add `ngrx`

### ISSUE THREAD

**Issue by fulls1z3** [fulls1z3/universal#52]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[x ] feature request
```

**Current behavior**
This project does not have any (*transient*) state management solution.

**Expected/desired behavior**
**ngrx** `v4.x` could be introduced.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
As well as being a seed project for Angular/SSR development, this project is also showcasing a bunch of angular libraries (*ngx-...*). Recently, I was asked about the compability of `@ngx-config/core` with **ngrx** `v4.x` (https://github.com/ngx-config/core/issues/18), and I think introducing **ngrx** to this project will both answer the compability issues as well as managing the state.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by dr1ss** [comment]
This would be pretty cool indeed

**Comment by fulls1z3** [comment]
@dr1ss I think within two weeks, we'll be there.. Soon I'll upload a list of tasks, and everybody will be able to track the status.

**Comment by fulls1z3** [comment]
@dr1ss done, have a look when u have time and feel free to make your comments

**Comment by fulls1z3** [comment]
Also, closes https://github.com/fulls1z3/ngx-config/issues/18
