### ISSUE TITLE
func expressions not supported in decorators in reducers in aot

### ISSUE THREAD

**Issue by smadil997** [fulls1z3/universal#604]
ERROR in src\app\framework\store\i18n\i18n.module.ts(17,38): Error during template compile of 'I18NModule'
  Function expressions are not supported in decorators in 'reducer'
    'reducer' contains the error at src\app\framework\store\i18n\language\language.reducer.ts(9,24)
      Consider changing the function expression into an exported function.

**Comment by fulls1z3** [comment]
@smadil997, that's solved - just pull the latest
