### ISSUE TITLE
universal + UglifyJS + Third party libraries = fail in production ?

### ISSUE THREAD

**Issue by dr1ss** [fulls1z3/universal#61]
```
[ ] bug report => check the README and search github for a similar issue or PR before submitting
[ x] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**
The universal production compilation fails with various messages from uglifyJS depending on used libraries :

#### ERROR When using nodemailer ####
`
Error: server.js from UglifyJs
Unexpected token: operator (>) [server.js:16880,41]
    (1) error(s) total.
`
#### ERROR When using mongoose ####
`
Error: server.js from UglifyJs
Invalid assignment [server.js:206539,48]
    (1) error(s) total.
`
Tryed to upgrade UglifyJS harmony to the latest version, no luck

**Expected/desired behavior**
Compile correctly :)

**Minimal reproduction of the problem with instructions**
import and initiate 'mongoose' package

* **Angular version:** 4.3.0
* **Node (for AoT issues):** `node --version` =   8.4

**Comment by dr1ss** [comment]
Not sure what's the benefit of using uglifyJS for the server... I just ended up removing uglifyJS for the server side in angular-webpack-config

**Comment by fulls1z3** [comment]
@dr1ss which version of UglifyJS was included in your project? You should include `v2.8.22` of `harmony` branch for es6 compability, otherwise any version else than this will throw an error. Can you please confirm that you included the following package in your `package.json`?

```
"uglify-js": "git://github.com/mishoo/UglifyJS2#harmony-v2.8.22",
```

**Comment by dr1ss** [comment]
Hello,
just got back home.. so yeah that's what I'm using : UglifyJS2#harmony-v2.8.22
So in my case it seems like there is 2 different problems, the first (with nodemailer) is apparently linked to ES6 when I replaced it with nodemailer2 wich they say (https://www.npmjs.com/package/nodemailer2)  "with no ES6 shenanigans used that would break your production app" it compiles without any error.

The other compilation error (Error: server.js from UglifyJs Invalid assignment) I've absolutly no idea why this happens, I get these warnings before the error :  

`
Warning: ./node_modules/mongoose/lib/drivers/index.js
10:13-49 Critical dependency: the request of a dependency is an expression
Warning: ./node_modules/express/lib/view.js
79:29-41 Critical dependency: the request of a dependency is an expression
Warning: ./node_modules/require_optional/index.js
82:18-42 Critical dependency: the request of a dependency is an expression
Warning: ./node_modules/es6-promise/dist/es6-promise.js
Module not found: Error: Can't resolve 'vertx' in '/Volumes/Secondary/Boulot/Experiments/starters/universal/node_modules/es6-promise/dist'
`

**Comment by dr1ss** [comment]
New update.
Still have the warnings but no more 'Invalid assignment' compilation error.
I deleted the node_modules folder and reinstalled everything with npm. I was using yarn. 
I've no idea why yarn is the problem (I even cleared yarn's cache and reran the install but still got the same issue)

**Comment by fulls1z3** [comment]
@dr1ss now I see, some other deps might probably require a newer version of UglifyJS and that's the reason why you were getting these errors.

With minimal configuration/deps, it's fine with both yarn and npm.
