### ISSUE TITLE
is there an option to make the build watch the source and hotload changes?

### ISSUE THREAD

**Issue by ghost** [fulls1z3/universal#62]
Currently the build process each time I change something in either the client or the server is too long to be workable.

Is there a way to get the build process to watch the files and do a hot-module-replace or something? I'd like to be able to develop the server + client code at the same time.

**Comment by patrickmichalina** [comment]
My starter does it here:

https://github.com/patrickmichalina/fusebox-angular-universal-starter

**Comment by fulls1z3** [comment]
@TheRationalizer for the client platform, there's already the HMR support - but not yet for the server platform. Did you mean that?

@patrickmichalina I took a look at your repo, great job 👍

**Comment by ghost** [comment]
If you switch to using ts-node-dev instead of ts-node it will hotload your changes, it is pretty much instant.

https://www.npmjs.com/package/ts-node-dev

**Comment by fulls1z3** [comment]
@TheRationalizer seems like worth giving it a try ;)

**Comment by Quixomatic** [comment]
@TheRationalizer can you explain what changes you had to make? The readme on the repo isn't very informative for ts-node-dev

**Comment by fulls1z3** [comment]
@Quixomatic I'm testing some webpack tools for rapid rebuild (currently achieved ~750ms), in a few days you won't need to worry about that at all 😄 

![untitled-1](https://user-images.githubusercontent.com/19705684/30250253-af83bc92-9653-11e7-869b-188bab581319.png)

**Comment by mrpmorris** [comment]
I just did a global install of ts-node-dev and changed any reference to ts-node to ts-node-dev instead in my scripts

**Comment by ghost** [comment]
@Quixomatic do a global installation of ts-node-dev, and then edit your json files to use ts-node-dev instead of ts-node
