### ISSUE TITLE
how to set facebook og tags

### ISSUE THREAD

**Issue by smadil997** [fulls1z3/universal#634]
Hi can you please tell me how i can change facebook og tags like 
`<meta property="og:url"                content="http://www.nytimes.com/2015/02/19/arts/international/when-great-minds-dont-think-alike.html" />
<meta property="og:type"               content="article" />
<meta property="og:title"              content="When Great Minds Don’t Think Alike" />
<meta property="og:description"        content="How much does culture influence creative thinking?" />
<meta property="og:image"              content="http://static01.nyt.com/images/2015/02/19/arts/international/19iht-btnumbers19A/19iht-btnumbers19A-facebookJumbo-v2.jpg" />`

on particular components in project

**Comment by NKjoep** [comment]
Hi, you should have a look at the `Meta` service: https://angular.io/api/platform-browser/Meta

```ts
import { Meta } from '@angular/platform-browser';

class SomeService {
    constructor( private meta: Meta ) {}
    doStuff() {
        this.meta.addTag({
            property: 'og:type',
            content: 'article'
        });
    }
}


```
