### ISSUE TITLE
use angluar-cli

### ISSUE THREAD

**Issue by vlados** [fulls1z3/universal#64]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[x] Documentation issue or request
```
How we can create new component or service?

**Comment by fulls1z3** [comment]
@vlados unfortunately not, angular-cli does not allow using a custom webpack config. Actually that was the reason why I created this seed project.

**Comment by fulls1z3** [comment]
@vlados now we have best of both worlds: latest (*v4*) webpack + custom build config + **schematics** from `@angular` and `@ngrx`.

Feel free to use the following commands and let me know about the results:

```
# change the working dir
$ cd universal

# add module `todos`
$ ng g module todos
# create src/client/app/todos/todos.module.ts (183 bytes)

# add entity  `+todos/Item`
$ ng g entity +todos/Item
# create src/client/app/+item/item.actions.ts (2094 bytes)
# create src/client/app/+item/item.model.ts (40 bytes)
# create src/client/app/+item/item.reducer.ts (1746 bytes)
# create src/client/app/+item/item.reducer.spec.ts (322 bytes)
```

Meanwhile, it would be really nice if you could make a contribution to the documentation about the use of **CLI** and added **schematics** from `@angular` and `@ngrx`.

**Comment by vlados** [comment]
WOW! :) I will find some time and I will do it. Putting in the todos :)
