### ISSUE TITLE
is there some kind of documentation

### ISSUE THREAD

**Issue by vlados** [fulls1z3/universal#65]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[x] Documentation issue or request
```

I am having hard time to understand some of the things that you made. It will be very helpful if there is some kind of documentation or tutorial.

- For example why the components are named for example "+about"?
- How we can use the routes in each component?
- How we can use the server side rendering in production env?

**Comment by fulls1z3** [comment]
@vlados a better documentation is on its way, while pushing a few killer features to this repository. Probably within a few days, you'll have all these answers on the readme.

**Comment by vlados** [comment]
I am loving how you made angular on steroids 🥇  and I will be happy to contribute, once I understand it :)

**Comment by fulls1z3** [comment]
@vlados I always believe in giving to the open-source community by sharing some of the projects we build for our applications. Any contributions are always welcome 👍
