### ISSUE TITLE
server side render taking too much time 

### ISSUE THREAD

**Issue by rahulmodu** [fulls1z3/universal#81]
i am using your repo and injected my project into this repo after this on server side redering taking too much time to render .
I have not used lazyLoding . can you please tell  what problem is coming into my project

**Comment by fulls1z3** [comment]
@rahulmodu you're not alone, my builds are taking quite long time 😄 

Reducing build times a top priority, and planning a solution consisting of a few steps. The first one is going to be merged overnight - you can follow #79 and `build-dll` branch for more details.

**Comment by rahulmodu** [comment]
my question is rendering time taking too much time after building, my question is not making build.
