### ISSUE TITLE
using absolute path in templates 

### ISSUE THREAD

**Issue by rahulmodu** [fulls1z3/universal#82]
1. How can i use assets path in my project as absolute path.

e.g. gives me error in home.component.ts file => 
" src="assets/img/background.png" "

while this works fine =>
src="./../../../assets/img/background.png"

2. Also how can i use assets path in sass folder ? I want to use absolute path in sass files.

**Comment by fulls1z3** [comment]
@rahulmodu have a look at [angular-webpack-config](https://github.com/ng-seed/angular-webpack-config#-usage), setting the `publicPath` property of `build-config.json` from *relative* to *absolute* might help.
