### ISSUE TITLE
require webpack-dev-middleware package

### ISSUE THREAD

**Issue by deefactorial** [fulls1z3/universal#85]
if I run:

```sh
npm run serve:spa-hmr
```
I get the error `Error: Cannot find module 'webpack-dev-middleware'

I fixed it by running the command:

```sh
npm install webpack-dev-middleware --save-dev
```

**Comment by fulls1z3** [comment]
@deefactorial known issue, already included in `build-dll` branch as of yesterday. If things go alright, going to release `v1.0.0` overnight, and we'll use semantic versioning for further releases.

**Comment by deefactorial** [comment]
@fulls1z3 thank you for heads up, I'll look for the update. Thanks for all your great work on this project.
