### ISSUE TITLE
jquery and jquery related plugins usage

### ISSUE THREAD

**Issue by rahulmodu** [fulls1z3/universal#89]
i am getting error while using jquery , can not found any documentation related to usage in server side rending

**Comment by ahmed-anas** [comment]
when doing SSR you don't have the 'window' object so you cant use jquery. You'll need to use a bunch of ifstatements with browser checks.

**Comment by fulls1z3** [comment]
@rahulmodu @ahmed-anas I wanted to answer, but it seems like @ahmed-anas explained it so well 👍
