### ISSUE TITLE
some @types do not work with spa-dev build

### ISSUE THREAD

**Issue by ahmed-anas** [fulls1z3/universal#90]
**I'm submitting a ...**  (check one with "x")
```
[ * ] Regression (a behavior that used to work and stopped working in a new release)
[ * ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
```

**Current behavior**
`npm run build:spa-dev` with some typings (i.e `@types/google-maps`) does not work. gives error: `Error: Cannot find module '@types/google-maps'`
**Expected/desired behavior**
it should work

**Minimal reproduction of the problem with instructions**
in a fresh universal install do:
```
npm install -S @types/google-maps;
npm run build:spa-dev;
```

**Comment by fulls1z3** [comment]
@ahmed-anas I'll have a look on it soon.
